// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-59_LVV95Y-zlkQ4cRwWpsWq2lkU-uA',
    appId: '1:237051839469:web:a9b1ce526a94d9b9eb5de4',
    messagingSenderId: '237051839469',
    projectId: 'pushnotification-cb8c0',
    authDomain: 'pushnotification-cb8c0.firebaseapp.com',
    storageBucket: 'pushnotification-cb8c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1tkNdolsLVGV9vKv6D-Od48h-Q_kLAAI',
    appId: '1:237051839469:android:960f86699114b3b8eb5de4',
    messagingSenderId: '237051839469',
    projectId: 'pushnotification-cb8c0',
    storageBucket: 'pushnotification-cb8c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW0zen4S-BiUNus6Ydkvjfl2Z-yXdA_Tc',
    appId: '1:237051839469:ios:c89959f612166cc2eb5de4',
    messagingSenderId: '237051839469',
    projectId: 'pushnotification-cb8c0',
    storageBucket: 'pushnotification-cb8c0.appspot.com',
    iosClientId: '237051839469-7caji631t1sjffu6hu048f03jojd5pcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW0zen4S-BiUNus6Ydkvjfl2Z-yXdA_Tc',
    appId: '1:237051839469:ios:003b03b8110b6f90eb5de4',
    messagingSenderId: '237051839469',
    projectId: 'pushnotification-cb8c0',
    storageBucket: 'pushnotification-cb8c0.appspot.com',
    iosClientId: '237051839469-uecdrhe7ge0hm79b8r3g9348l3f70q85.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification.RunnerTests',
  );
}
